### ISSUE TITLE
Subtasks issue

### ISSUE THREAD

**Issue by maxim4** [anmarkoulis/clickup-to-jira#84]
When I run the migration from ClickUp to Jira, an error occurs during conversion if there are subtasks. The error message is: ‘AttributeError: ‘dict’ object has no attribute ‘name’’. This error is raised when the script tries to access the ‘name’ attribute of a ‘ticket’ object, which seems to be a dictionary in this context. It appears that the ‘ticket’ object does not have a ‘name’ attribute, causing the script to fail.

Traceback (most recent call last):
  File "/home/jira/clickup-to-jira/clickup_to_jira/scripts/migrate.py", line 36, in <module>
    main()
  File "/home/jira/clickup-to-jira/clickup_to_jira/scripts/migrate.py", line 29, in main
    new_tickets = converter.convert(tickets)
  File "/home/jira/.local/lib/python3.10/site-packages/clickup_to_jira/converter.py", line 34, in convert
    converted_tickets.append(self.convert_ticket(ticket))
  File "/home/jira/.local/lib/python3.10/site-packages/clickup_to_jira/converter.py", line 57, in convert_ticket
    subtasks = self._get_converted_subtasks(ticket.linked_tasks)
  File "/home/jira/.local/lib/python3.10/site-packages/clickup_to_jira/converter.py", line 105, in _get_converted_subtasks
    return [self.convert_ticket(subtask) for subtask in subtasks]
  File "/home/jira/.local/lib/python3.10/site-packages/clickup_to_jira/converter.py", line 105, in <listcomp>
    return [self.convert_ticket(subtask) for subtask in subtasks]
  File "/home/jira/.local/lib/python3.10/site-packages/clickup_to_jira/converter.py", line 49, in convert_ticket
    logger.info(f"converting ticket {ticket.name}")
AttributeError: 'dict' object has no attribute 'name'

**Comment by boris-lapouga** [comment]
Seems like this repository is not maintained. Getting the same error.
